# Generated by Django 6.0.4 on 2026-04-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('codigo_interno', models.CharField(max_length=50, unique=True, verbose_name='Código (Tag)')),
                ('marca', models.CharField(max_length=50)),
                ('fecha_instalacion', models.DateField(verbose_name='Fecha de Instalación')),
                ('criticidad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=5)),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
            },
        ),
    ]
