# Generated by Django 6.0.4 on 2026-05-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'equipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estrategias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estrategias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventosFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_id', models.IntegerField(blank=True, null=True)),
                ('descripcion_problema', models.TextField()),
                ('prioridad', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_reporte', models.DateTimeField(blank=True, null=True)),
                ('reportado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('ot_generada_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eventos_falla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horometros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_acumulado', models.IntegerField()),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'horometros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenesTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ordenes_trabajo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tarea', models.TextField()),
                ('frecuencia_horas', models.IntegerField()),
                ('ultimo_mantenimiento_horas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'planes',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Activo',
        ),
    ]
